name: Compile and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Gradle
      run: |
        ./gradlew build
#        ./gradlew upload
        ./gradlew -Pgpr.user=balazskreith -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
#    - name: Publish artifact
#      env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
#        # If we split on '/' and take the 3rd value,
#        # we can get the release name.
#      run: |
#          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
#          echo "New version: ${NEW_VERSION}"
#          echo "Github username: ${GITHUB_ACTOR}"
#          ./gradlew -Pversion=${NEW_VERSION} publish
